import { normalizeMeal } from './schema';

function meal(partial) {
  return normalizeMeal({
    source: 'catalog',
    servings: 1,
    ...partial,
    catalogKey: partial.catalogKey,
  });
}

function ing(name, quantity, unit, category, estimatedCost, extras = {}) {
  return { name, quantity, unit, category, estimatedCost, ...extras };
}

export const NUTRITION_CATALOG = [
  meal({
    catalogKey: 'yogurt-honey-berries',
    name: 'Greek yogurt, berries & walnuts',
    mealType: 'breakfast',
    calories: 420,
    protein: 32,
    carbs: 38,
    fat: 16,
    prepTimeMin: 8,
    instructions: 'Spoon yogurt into a bowl. Add berries, walnuts and honey. No cooking.',
    tags: ['no-cook', 'high-protein', 'quick'],
    allergens: ['dairy', 'nuts'],
    diets: ['mediterranean', 'high_protein', 'vegetarian', 'gluten_free'],
    equipment: ['no_cook'],
    ingredients: [
      ing('Greek yogurt 2%', 200, 'g', 'Dairy', 0.9),
      ing('Mixed berries', 80, 'g', 'Produce', 0.7),
      ing('Walnuts', 20, 'g', 'Pantry', 0.45),
      ing('Honey', 10, 'g', 'Pantry', 0.12),
    ],
  }),
  meal({
    catalogKey: 'oat-banana-pb',
    name: 'Oat porridge with banana',
    mealType: 'breakfast',
    calories: 480,
    protein: 22,
    carbs: 68,
    fat: 14,
    prepTimeMin: 12,
    instructions: 'Simmer oats in milk 6–8 min. Stir in protein powder off heat. Top with banana and peanut butter.',
    tags: ['warm', 'budget'],
    allergens: ['gluten', 'dairy', 'peanuts'],
    diets: ['high_protein', 'vegetarian'],
    equipment: ['stovetop'],
    ingredients: [
      ing('Rolled oats', 60, 'g', 'Grains', 0.18),
      ing('Milk 1.5%', 250, 'ml', 'Dairy', 0.3),
      ing('Banana', 1, 'pcs', 'Produce', 0.25),
      ing('Peanut butter', 16, 'g', 'Pantry', 0.2),
      ing('Whey protein', 15, 'g', 'Pantry', 0.4),
    ],
  }),
  meal({
    catalogKey: 'veg-omelette-feta',
    name: 'Veg omelette with feta',
    mealType: 'breakfast',
    calories: 390,
    protein: 28,
    carbs: 8,
    fat: 27,
    prepTimeMin: 15,
    instructions: 'Sauté spinach and tomato. Pour beaten eggs, add feta, fold. Cook until just set.',
    tags: ['high-protein', 'low-carb', 'savory'],
    allergens: ['eggs', 'dairy'],
    diets: ['mediterranean', 'high_protein', 'vegetarian', 'low_carb', 'gluten_free'],
    equipment: ['stovetop'],
    ingredients: [
      ing('Eggs', 3, 'pcs', 'Dairy', 0.6),
      ing('Spinach', 60, 'g', 'Produce', 0.25),
      ing('Tomato', 80, 'g', 'Produce', 0.2),
      ing('Feta', 30, 'g', 'Dairy', 0.4),
      ing('Olive oil', 8, 'ml', 'Pantry', 0.12),
    ],
  }),
  meal({
    catalogKey: 'overnight-oats-plant',
    name: 'Overnight oats with plant milk',
    mealType: 'breakfast',
    calories: 430,
    protein: 18,
    carbs: 62,
    fat: 13,
    prepTimeMin: 6,
    instructions: 'Mix oats, plant milk, chia and maple. Chill overnight. Top with apple in the morning.',
    tags: ['prep', 'vegan', 'no-cook'],
    allergens: ['gluten'],
    diets: ['vegan', 'vegetarian', 'dairy_free'],
    equipment: ['no_cook'],
    ingredients: [
      ing('Rolled oats', 70, 'g', 'Grains', 0.2),
      ing('Oat milk', 220, 'ml', 'Dairy', 0.35),
      ing('Chia seeds', 12, 'g', 'Pantry', 0.22),
      ing('Apple', 1, 'pcs', 'Produce', 0.3),
      ing('Maple syrup', 8, 'g', 'Pantry', 0.15),
    ],
  }),
  meal({
    catalogKey: 'cottage-cucumber',
    name: 'Cottage cheese cucumber bowl',
    mealType: 'breakfast',
    calories: 340,
    protein: 34,
    carbs: 12,
    fat: 16,
    prepTimeMin: 7,
    instructions: 'Mix cottage cheese with cucumber, olive oil, oregano and pepper. Serve cold.',
    tags: ['no-cook', 'high-protein', 'quick'],
    allergens: ['dairy'],
    diets: ['high_protein', 'low_carb', 'vegetarian', 'gluten_free', 'mediterranean'],
    equipment: ['no_cook'],
    ingredients: [
      ing('Cottage cheese', 200, 'g', 'Dairy', 1.1),
      ing('Cucumber', 120, 'g', 'Produce', 0.2),
      ing('Olive oil', 8, 'ml', 'Pantry', 0.12),
      ing('Oregano', 1, 'g', 'Pantry', 0.02),
    ],
  }),
  meal({
    catalogKey: 'avocado-egg-toast',
    name: 'Eggs & avocado on toast',
    mealType: 'breakfast',
    calories: 510,
    protein: 24,
    carbs: 36,
    fat: 30,
    prepTimeMin: 12,
    instructions: 'Toast bread. Mash avocado with lemon. Fry or boil eggs and assemble.',
    tags: ['classic'],
    allergens: ['gluten', 'eggs'],
    diets: ['vegetarian', 'mediterranean'],
    equipment: ['stovetop'],
    ingredients: [
      ing('Wholegrain bread', 70, 'g', 'Grains', 0.28),
      ing('Eggs', 2, 'pcs', 'Dairy', 0.4),
      ing('Avocado', 80, 'g', 'Produce', 0.7),
      ing('Lemon', 0.25, 'pcs', 'Produce', 0.1),
      ing('Olive oil', 5, 'ml', 'Pantry', 0.08),
    ],
  }),
  meal({
    catalogKey: 'chicken-rice-bowl',
    name: 'Chicken rice bowl',
    mealType: 'lunch',
    calories: 620,
    protein: 48,
    carbs: 62,
    fat: 16,
    prepTimeMin: 30,
    instructions: 'Grill or pan-cook chicken. Boil rice. Serve with cucumber-tomato salad and olive oil.',
    tags: ['high-protein', 'batch', 'reuse'],
    allergens: [],
    diets: ['high_protein', 'mediterranean', 'gluten_free'],
    equipment: ['stovetop', 'grill'],
    ingredients: [
      ing('Chicken breast', 180, 'g', 'Meat', 1.8),
      ing('White rice', 70, 'g', 'Grains', 0.18),
      ing('Cucumber', 80, 'g', 'Produce', 0.15),
      ing('Tomato', 80, 'g', 'Produce', 0.2),
      ing('Olive oil', 10, 'ml', 'Pantry', 0.15),
      ing('Lemon', 0.25, 'pcs', 'Produce', 0.1),
    ],
  }),
  meal({
    catalogKey: 'lentil-soup',
    name: 'Lentil soup',
    mealType: 'lunch',
    calories: 480,
    protein: 24,
    carbs: 64,
    fat: 12,
    prepTimeMin: 40,
    instructions: 'Sauté onion and carrot. Add lentils, tomato paste and water. Simmer 30 min. Finish with olive oil.',
    tags: ['budget', 'vegan', 'batch'],
    allergens: [],
    diets: ['vegan', 'vegetarian', 'mediterranean', 'dairy_free'],
    equipment: ['stovetop'],
    ingredients: [
      ing('Brown lentils', 90, 'g', 'Pantry', 0.35),
      ing('Onion', 80, 'g', 'Produce', 0.12),
      ing('Carrot', 80, 'g', 'Produce', 0.15),
      ing('Tomato paste', 20, 'g', 'Pantry', 0.12),
      ing('Olive oil', 12, 'ml', 'Pantry', 0.18),
      ing('Wholegrain bread', 40, 'g', 'Grains', 0.16),
    ],
  }),
  meal({
    catalogKey: 'salmon-potato-greens',
    name: 'Salmon, potatoes & greens',
    mealType: 'dinner',
    calories: 640,
    protein: 42,
    carbs: 38,
    fat: 32,
    prepTimeMin: 28,
    instructions: 'Roast salmon and potatoes at 200°C for 18–22 min. Steam or sauté greens with garlic.',
    tags: ['omega-3', 'high-protein'],
    allergens: ['fish'],
    diets: ['mediterranean', 'high_protein', 'pescatarian', 'gluten_free'],
    equipment: ['oven', 'stovetop'],
    ingredients: [
      ing('Salmon fillet', 160, 'g', 'Fish', 3.2),
      ing('Baby potatoes', 200, 'g', 'Produce', 0.4),
      ing('Broccoli', 150, 'g', 'Produce', 0.45),
      ing('Olive oil', 10, 'ml', 'Pantry', 0.15),
      ing('Garlic', 6, 'g', 'Produce', 0.06),
    ],
  }),
  meal({
    catalogKey: 'chicken-souvlaki-wrap',
    name: 'Chicken souvlaki wrap',
    mealType: 'lunch',
    calories: 590,
    protein: 44,
    carbs: 48,
    fat: 22,
    prepTimeMin: 25,
    instructions: 'Cook marinated chicken strips. Warm pita. Fill with tomato, onion, yogurt and chicken.',
    tags: ['greek', 'high-protein'],
    allergens: ['gluten', 'dairy'],
    diets: ['mediterranean', 'high_protein'],
    equipment: ['stovetop', 'grill'],
    ingredients: [
      ing('Chicken breast', 160, 'g', 'Meat', 1.6),
      ing('Pita bread', 1, 'pcs', 'Grains', 0.4),
      ing('Greek yogurt 2%', 60, 'g', 'Dairy', 0.28),
      ing('Tomato', 70, 'g', 'Produce', 0.18),
      ing('Red onion', 30, 'g', 'Produce', 0.08),
      ing('Olive oil', 8, 'ml', 'Pantry', 0.12),
    ],
  }),
  meal({
    catalogKey: 'chickpea-salad',
    name: 'Chickpea chopped salad',
    mealType: 'lunch',
    calories: 520,
    protein: 22,
    carbs: 54,
    fat: 22,
    prepTimeMin: 15,
    instructions: 'Drain chickpeas. Chop vegetables. Toss with olive oil, lemon and herbs.',
    tags: ['vegan', 'no-cook', 'prep'],
    allergens: [],
    diets: ['vegan', 'vegetarian', 'mediterranean', 'dairy_free', 'gluten_free'],
    equipment: ['no_cook'],
    ingredients: [
      ing('Chickpeas canned', 200, 'g', 'Pantry', 0.55),
      ing('Cucumber', 100, 'g', 'Produce', 0.18),
      ing('Tomato', 120, 'g', 'Produce', 0.28),
      ing('Red onion', 40, 'g', 'Produce', 0.1),
      ing('Olive oil', 15, 'ml', 'Pantry', 0.22),
      ing('Lemon', 0.5, 'pcs', 'Produce', 0.18),
      ing('Parsley', 10, 'g', 'Produce', 0.12),
    ],
  }),
  meal({
    catalogKey: 'tuna-pasta',
    name: 'Tuna lemon pasta',
    mealType: 'lunch',
    calories: 610,
    protein: 38,
    carbs: 68,
    fat: 18,
    prepTimeMin: 20,
    instructions: 'Boil pasta. Toss with tuna, olive oil, lemon, garlic and parsley. Serve warm or cold.',
    tags: ['budget', 'quick'],
    allergens: ['gluten', 'fish'],
    diets: ['pescatarian', 'high_protein', 'mediterranean'],
    equipment: ['stovetop'],
    ingredients: [
      ing('Pasta', 90, 'g', 'Grains', 0.25),
      ing('Tuna in water', 120, 'g', 'Fish', 1.4),
      ing('Olive oil', 12, 'ml', 'Pantry', 0.18),
      ing('Lemon', 0.4, 'pcs', 'Produce', 0.15),
      ing('Garlic', 4, 'g', 'Produce', 0.04),
      ing('Parsley', 8, 'g', 'Produce', 0.1),
    ],
  }),
  meal({
    catalogKey: 'beef-rice-salad',
    name: 'Lean beef with rice',
    mealType: 'dinner',
    calories: 680,
    protein: 46,
    carbs: 58,
    fat: 26,
    prepTimeMin: 30,
    instructions: 'Brown beef with onion. Season. Serve over rice with a simple salad.',
    tags: ['high-protein', 'reuse'],
    allergens: [],
    diets: ['high_protein', 'gluten_free'],
    equipment: ['stovetop'],
    ingredients: [
      ing('Lean beef mince', 160, 'g', 'Meat', 2.1),
      ing('White rice', 70, 'g', 'Grains', 0.18),
      ing('Onion', 60, 'g', 'Produce', 0.1),
      ing('Tomato', 80, 'g', 'Produce', 0.2),
      ing('Lettuce', 60, 'g', 'Produce', 0.2),
      ing('Olive oil', 8, 'ml', 'Pantry', 0.12),
    ],
  }),
  meal({
    catalogKey: 'baked-cod-veg',
    name: 'Baked cod with vegetables',
    mealType: 'dinner',
    calories: 430,
    protein: 38,
    carbs: 22,
    fat: 18,
    prepTimeMin: 25,
    instructions: 'Bake cod with olive oil and lemon. Roast zucchini and peppers on the same tray.',
    tags: ['light', 'high-protein'],
    allergens: ['fish'],
    diets: ['pescatarian', 'mediterranean', 'low_carb', 'gluten_free', 'high_protein'],
    equipment: ['oven'],
    ingredients: [
      ing('Cod fillet', 180, 'g', 'Fish', 2.6),
      ing('Zucchini', 150, 'g', 'Produce', 0.35),
      ing('Bell pepper', 120, 'g', 'Produce', 0.4),
      ing('Olive oil', 12, 'ml', 'Pantry', 0.18),
      ing('Lemon', 0.4, 'pcs', 'Produce', 0.15),
    ],
  }),
  meal({
    catalogKey: 'chicken-stir-fry',
    name: 'Chicken vegetable stir-fry',
    mealType: 'dinner',
    calories: 560,
    protein: 46,
    carbs: 28,
    fat: 28,
    prepTimeMin: 22,
    instructions: 'Stir-fry chicken, then vegetables on high heat. Add soy or lemon. Serve with a small portion of rice.',
    tags: ['quick', 'high-protein'],
    allergens: ['soy'],
    diets: ['high_protein', 'dairy_free'],
    equipment: ['stovetop'],
    ingredients: [
      ing('Chicken breast', 170, 'g', 'Meat', 1.7),
      ing('Broccoli', 120, 'g', 'Produce', 0.36),
      ing('Bell pepper', 80, 'g', 'Produce', 0.28),
      ing('White rice', 40, 'g', 'Grains', 0.1),
      ing('Olive oil', 10, 'ml', 'Pantry', 0.15),
      ing('Soy sauce', 10, 'ml', 'Pantry', 0.08),
    ],
  }),
  meal({
    catalogKey: 'turkey-orzo',
    name: 'Turkey meatballs with orzo',
    mealType: 'dinner',
    calories: 640,
    protein: 44,
    carbs: 58,
    fat: 22,
    prepTimeMin: 35,
    instructions: 'Mix turkey with herbs, form small meatballs, bake. Simmer orzo. Combine with tomato sauce.',
    tags: ['batch', 'family'],
    allergens: ['gluten', 'eggs'],
    diets: ['high_protein', 'mediterranean'],
    equipment: ['oven', 'stovetop'],
    ingredients: [
      ing('Turkey mince', 160, 'g', 'Meat', 1.9),
      ing('Orzo', 70, 'g', 'Grains', 0.22),
      ing('Tomato passata', 120, 'g', 'Pantry', 0.3),
      ing('Egg', 0.5, 'pcs', 'Dairy', 0.1),
      ing('Onion', 40, 'g', 'Produce', 0.08),
      ing('Olive oil', 8, 'ml', 'Pantry', 0.12),
    ],
  }),
  meal({
    catalogKey: 'greek-salad-chicken',
    name: 'Greek salad with grilled chicken',
    mealType: 'lunch',
    calories: 540,
    protein: 42,
    carbs: 16,
    fat: 34,
    prepTimeMin: 20,
    instructions: 'Grill chicken. Assemble tomato, cucumber, onion, olives and feta. Dress with olive oil.',
    tags: ['greek', 'low-carb'],
    allergens: ['dairy'],
    diets: ['mediterranean', 'high_protein', 'low_carb', 'gluten_free'],
    equipment: ['grill', 'stovetop'],
    ingredients: [
      ing('Chicken breast', 160, 'g', 'Meat', 1.6),
      ing('Tomato', 120, 'g', 'Produce', 0.28),
      ing('Cucumber', 100, 'g', 'Produce', 0.18),
      ing('Feta', 40, 'g', 'Dairy', 0.55),
      ing('Kalamata olives', 20, 'g', 'Pantry', 0.25),
      ing('Olive oil', 12, 'ml', 'Pantry', 0.18),
      ing('Red onion', 30, 'g', 'Produce', 0.08),
    ],
  }),
  meal({
    catalogKey: 'fasolada',
    name: 'Bean stew (fasolada)',
    mealType: 'dinner',
    calories: 520,
    protein: 22,
    carbs: 70,
    fat: 14,
    prepTimeMin: 45,
    instructions: 'Simmer soaked or canned beans with carrot, celery, onion and tomato. Finish with olive oil.',
    tags: ['vegan', 'budget', 'batch'],
    allergens: [],
    diets: ['vegan', 'vegetarian', 'mediterranean', 'dairy_free'],
    equipment: ['stovetop'],
    ingredients: [
      ing('White beans canned', 220, 'g', 'Pantry', 0.6),
      ing('Carrot', 80, 'g', 'Produce', 0.15),
      ing('Celery', 40, 'g', 'Produce', 0.12),
      ing('Onion', 70, 'g', 'Produce', 0.1),
      ing('Tomato paste', 20, 'g', 'Pantry', 0.12),
      ing('Olive oil', 14, 'ml', 'Pantry', 0.2),
    ],
  }),
  meal({
    catalogKey: 'chicken-thighs-broccoli',
    name: 'Baked chicken thighs & broccoli',
    mealType: 'dinner',
    calories: 610,
    protein: 46,
    carbs: 14,
    fat: 40,
    prepTimeMin: 35,
    instructions: 'Season thighs, bake 30 min at 200°C. Roast broccoli on the same tray for the last 15 min.',
    tags: ['sheet-pan', 'high-protein'],
    allergens: [],
    diets: ['high_protein', 'low_carb', 'gluten_free', 'mediterranean'],
    equipment: ['oven'],
    ingredients: [
      ing('Chicken thighs', 200, 'g', 'Meat', 1.7),
      ing('Broccoli', 180, 'g', 'Produce', 0.5),
      ing('Olive oil', 12, 'ml', 'Pantry', 0.18),
      ing('Lemon', 0.3, 'pcs', 'Produce', 0.12),
      ing('Garlic', 6, 'g', 'Produce', 0.06),
    ],
  }),
  meal({
    catalogKey: 'quinoa-veg-bowl',
    name: 'Quinoa vegetable bowl',
    mealType: 'lunch',
    calories: 500,
    protein: 18,
    carbs: 64,
    fat: 18,
    prepTimeMin: 25,
    instructions: 'Cook quinoa. Roast or steam vegetables. Assemble with olive oil and lemon.',
    tags: ['vegan', 'prep'],
    allergens: [],
    diets: ['vegan', 'vegetarian', 'dairy_free', 'gluten_free', 'mediterranean'],
    equipment: ['stovetop', 'oven'],
    ingredients: [
      ing('Quinoa', 70, 'g', 'Grains', 0.45),
      ing('Zucchini', 120, 'g', 'Produce', 0.28),
      ing('Chickpeas canned', 80, 'g', 'Pantry', 0.22),
      ing('Spinach', 50, 'g', 'Produce', 0.2),
      ing('Olive oil', 12, 'ml', 'Pantry', 0.18),
      ing('Lemon', 0.3, 'pcs', 'Produce', 0.12),
    ],
  }),
  meal({
    catalogKey: 'halloumi-salad',
    name: 'Grilled halloumi salad',
    mealType: 'dinner',
    calories: 560,
    protein: 28,
    carbs: 18,
    fat: 42,
    prepTimeMin: 18,
    instructions: 'Grill halloumi 2 min per side. Serve over tomato, cucumber and greens with olive oil.',
    tags: ['vegetarian', 'quick'],
    allergens: ['dairy'],
    diets: ['vegetarian', 'mediterranean', 'low_carb', 'gluten_free'],
    equipment: ['grill', 'stovetop'],
    ingredients: [
      ing('Halloumi', 90, 'g', 'Dairy', 1.4),
      ing('Tomato', 120, 'g', 'Produce', 0.28),
      ing('Cucumber', 100, 'g', 'Produce', 0.18),
      ing('Lettuce', 70, 'g', 'Produce', 0.22),
      ing('Olive oil', 12, 'ml', 'Pantry', 0.18),
    ],
  }),
  meal({
    catalogKey: 'protein-smoothie',
    name: 'Protein smoothie',
    mealType: 'snack',
    calories: 280,
    protein: 28,
    carbs: 26,
    fat: 6,
    prepTimeMin: 5,
    instructions: 'Blend milk, banana, protein powder and ice until smooth.',
    tags: ['quick', 'blender'],
    allergens: ['dairy'],
    diets: ['high_protein', 'vegetarian', 'gluten_free'],
    equipment: ['blender'],
    ingredients: [
      ing('Milk 1.5%', 250, 'ml', 'Dairy', 0.3),
      ing('Banana', 0.5, 'pcs', 'Produce', 0.13),
      ing('Whey protein', 25, 'g', 'Pantry', 0.65),
    ],
  }),
  meal({
    catalogKey: 'apple-almond-butter',
    name: 'Apple & almond butter',
    mealType: 'snack',
    calories: 220,
    protein: 6,
    carbs: 24,
    fat: 12,
    prepTimeMin: 3,
    instructions: 'Slice apple and serve with almond butter. No cooking.',
    tags: ['no-cook', 'quick'],
    allergens: ['nuts'],
    diets: ['vegetarian', 'vegan', 'gluten_free', 'dairy_free'],
    equipment: ['no_cook'],
    ingredients: [
      ing('Apple', 1, 'pcs', 'Produce', 0.3),
      ing('Almond butter', 16, 'g', 'Pantry', 0.4),
    ],
  }),
  meal({
    catalogKey: 'yogurt-granola',
    name: 'Yogurt & granola cup',
    mealType: 'snack',
    calories: 260,
    protein: 18,
    carbs: 32,
    fat: 7,
    prepTimeMin: 4,
    instructions: 'Layer yogurt and granola. Add a few berries if available.',
    tags: ['no-cook'],
    allergens: ['dairy', 'gluten'],
    diets: ['vegetarian', 'high_protein'],
    equipment: ['no_cook'],
    ingredients: [
      ing('Greek yogurt 2%', 150, 'g', 'Dairy', 0.7),
      ing('Granola', 30, 'g', 'Grains', 0.35),
      ing('Mixed berries', 40, 'g', 'Produce', 0.35),
    ],
  }),
  meal({
    catalogKey: 'cottage-snack',
    name: 'Cottage cheese & cucumber',
    mealType: 'snack',
    calories: 190,
    protein: 22,
    carbs: 8,
    fat: 7,
    prepTimeMin: 4,
    instructions: 'Serve cottage cheese with sliced cucumber and black pepper.',
    tags: ['no-cook', 'high-protein'],
    allergens: ['dairy'],
    diets: ['high_protein', 'low_carb', 'vegetarian', 'gluten_free'],
    equipment: ['no_cook'],
    ingredients: [
      ing('Cottage cheese', 150, 'g', 'Dairy', 0.85),
      ing('Cucumber', 80, 'g', 'Produce', 0.15),
    ],
  }),
  meal({
    catalogKey: 'tuna-white-beans',
    name: 'Tuna & white bean bowl',
    mealType: 'lunch',
    calories: 500,
    protein: 40,
    carbs: 36,
    fat: 18,
    prepTimeMin: 10,
    instructions: 'Mix tuna, beans, onion, lemon and olive oil. Eat cold.',
    tags: ['no-cook', 'high-protein', 'prep'],
    allergens: ['fish'],
    diets: ['pescatarian', 'high_protein', 'mediterranean', 'gluten_free', 'dairy_free'],
    equipment: ['no_cook'],
    ingredients: [
      ing('Tuna in water', 120, 'g', 'Fish', 1.4),
      ing('White beans canned', 150, 'g', 'Pantry', 0.4),
      ing('Red onion', 30, 'g', 'Produce', 0.08),
      ing('Olive oil', 10, 'ml', 'Pantry', 0.15),
      ing('Lemon', 0.3, 'pcs', 'Produce', 0.12),
    ],
  }),
  meal({
    catalogKey: 'pork-sweet-potato',
    name: 'Pork tenderloin & sweet potato',
    mealType: 'dinner',
    calories: 630,
    protein: 44,
    carbs: 42,
    fat: 28,
    prepTimeMin: 35,
    instructions: 'Roast pork and cubed sweet potato at 200°C until pork is cooked through. Rest 5 min.',
    tags: ['sheet-pan'],
    allergens: [],
    diets: ['high_protein', 'gluten_free', 'dairy_free'],
    equipment: ['oven'],
    ingredients: [
      ing('Pork tenderloin', 170, 'g', 'Meat', 2.2),
      ing('Sweet potato', 200, 'g', 'Produce', 0.45),
      ing('Olive oil', 10, 'ml', 'Pantry', 0.15),
      ing('Garlic', 6, 'g', 'Produce', 0.06),
    ],
  }),
  meal({
    catalogKey: 'plant-smoothie',
    name: 'Plant protein smoothie',
    mealType: 'snack',
    calories: 260,
    protein: 22,
    carbs: 30,
    fat: 6,
    prepTimeMin: 5,
    instructions: 'Blend oat milk, banana, plant protein and ice.',
    tags: ['vegan', 'blender'],
    allergens: [],
    diets: ['vegan', 'vegetarian', 'dairy_free'],
    equipment: ['blender'],
    ingredients: [
      ing('Oat milk', 250, 'ml', 'Dairy', 0.4),
      ing('Banana', 0.5, 'pcs', 'Produce', 0.13),
      ing('Pea protein', 25, 'g', 'Pantry', 0.7),
    ],
  }),
];

export function catalogByKey() {
  return new Map(NUTRITION_CATALOG.map((item) => [item.catalogKey, item]));
}

export function seedLibraryMeals(existing = []) {
  const have = new Set(existing.map((item) => item.catalogKey).filter(Boolean));
  const seeded = NUTRITION_CATALOG
    .filter((item) => !have.has(item.catalogKey))
    .map((item) => normalizeMeal({ ...item, id: item.id, source: 'catalog', favorite: false }));
  return [...existing, ...seeded];
}
